### PR TITLE
Fix Loading HTML with Custom Tags

### LINKED ISSUE #564: Loading content with custom attachment tags issue
I think there's an issue with loading existing that that uses a custom attachment tag. The attachment gets purged when setting the value of the editor. I _think_ I was able to reproduce it here: https://github.com/basecamp/lexxy/pull/563

Anyone else running into this?

### PR DESCRIPTION
**Pull request by tonysm**
### Fixed

- There was a race condition between registering the element and overriding global configs that prevented things from overriding the attachment tag name from working correctly. This PR fixes it by deferring the initialization of the elements so it runs after everything runs on the main call stack, which allows the configuration to take place before the elements init. 

---

closes #564

### CODE REVIEW

**Comment by tonysm** [comment]
I left a note on the issue with step to reproduce it manually too (besides the automated test included here): https://github.com/basecamp/lexxy/issues/564#issuecomment-3779714619

File: src/elements/index.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    "lexxy-prompt": Prompt,
+    "lexxy-code-language-picker": CodeLanguagePicker,
+    "lexxy-table-tools": TableTools,
+  }
+
+  Object.entries(elements).forEach(([ name, element ]) => {
+    if (!customElements.get(name)) {
+      customElements.define(name, element)
+    }
+  })
```
Comment (samuelpecher) [inline src/elements/index.js:23]: I think it's best not to guard re-registration, which in most cases would be an error?

```suggestion
  Object.entries(elements).forEach(([ name, element ]) => {
    customElements.define(name, element)
  })
```

File: src/elements/index.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
+import Toolbar from "./toolbar"
+
+import Editor from "./editor"
+import DropdownLink from "./dropdown/link"
+import DropdownHighlight from "./dropdown/highlight"
+import Prompt from "./prompt"
+import CodeLanguagePicker from "./code_language_picker"
+import TableTools from "./table/table_tools"
+
+export function start() {
```
Comment (samuelpecher) [inline src/elements/index.js]: I'd lean to a more descriptive name like `defineElements`.

File: src/index.js [hunk 3]
```diff
@@ -21,3 +13,5 @@ export { default as Extension } from "./extensions/lexxy_extension"
 
 // legacy export for <=v0.7
 export { highlightCode as highlightAll } from "./helpers/code_highlighting_helper"
+
+setTimeout(start, 0)
```
Comment (samuelpecher) [inline src/index.js]: This would be a great place to document the reasoning for the timeout!

**Comment by samuelpecher** [comment]
While I back this approach over an explicit `Lexxy.init()`, it's worth being aware we're not totally removing the race condition. There's an implied requirement to configure Lexxy synchronously after import. 

@tonysm would you be up to making this requirement explicit in the docs?

File: src/index.js (hunk 3 above)
Comment (tonysm) [reply src/index.js]: I've added a comment on why, let me know if that's clear enough

**Comment by tonysm** [comment]
@samuelpecher I've handled the suggestions and added a notice to the documentation on the importance of calling configure right after importing the lexxy module and why. Let me know if there's anything else you'd want to see changed.

File: src/elements/table/table_controller.js [hunk 4]
```diff
@@ -367,3 +367,4 @@ export class TableController {
     return true
   }
 }
+
```
Comment (samuelpecher) [inline src/elements/table/table_controller.js]: :scissors: 
```suggestion
```
